language: go

os:
  - linux
  - osx

go:
  - 1.8
  - 1.9
  - master

osx_image: xcode9.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  - go get github.com/mattn/go-sqlite3
  - go install github.com/mattn/go-sqlite3

script:
  - make test
